export default [
    {
        id:self.crypto.randomUUID(),
        title:'milk',
        category:'Grocery',
        amount:40
    },
    {
        id:self.crypto.randomUUID(),
        title:'hp',
        category:'laptop',
        amount:200
    },
    {
        id:self.crypto.randomUUID(),
        title:'bed',
        category:'forniture',
        amount:500
    },
    {
        id:self.crypto.randomUUID(),
        title:'shoes',
        category:'footwear',
        amount:100
    },
]